'use strict';var _typeof='function'==typeof Symbol&&'symbol'==typeof Symbol.iterator?function(obj){return typeof obj}:function(obj){return obj&&'function'==typeof Symbol&&obj.constructor===Symbol&&obj!==Symbol.prototype?'symbol':typeof obj},_createClass=function(){function defineProperties(target,props){for(var descriptor,i=0;i<props.length;i++)descriptor=props[i],descriptor.enumerable=descriptor.enumerable||!1,descriptor.configurable=!0,'value'in descriptor&&(descriptor.writable=!0),Object.defineProperty(target,descriptor.key,descriptor)}return function(Constructor,protoProps,staticProps){return protoProps&&defineProperties(Constructor.prototype,protoProps),staticProps&&defineProperties(Constructor,staticProps),Constructor}}();function _toConsumableArray(arr){if(Array.isArray(arr)){for(var i=0,arr2=Array(arr.length);i<arr.length;i++)arr2[i]=arr[i];return arr2}return Array.from(arr)}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError('Cannot call a class as a function')}/*!
*  formatrix 0.4.4 (http://formatrix.org)
*  >> PageConstructor 0.2.0
*
*  Copyright (c) 2016-2020 Germo Moeller / webons.industries
*
*  This source code is licensed under the MIT license found in the
*  LICENSE file in the root directory of this source tree.
*
*////***************************************************************************>
(function(fx){var $=new fx(fx.vbind('lib://webons.io/fx/PageConstructor/')+'events');$.prv={$:{lid:0,reg:{}},events:function(){function events($rid,$eid){_classCallCheck(this,events);var $lid=0;this.$={get rid(){return $rid},get eid(){return $eid},get lid(){return++$lid,$lid}},this.name=name,this.callbacks={}}return _createClass(events,[{key:'setCallback',value:function setCallback(callback,position){var $this=this,cid=this.$.lid;return null==position&&(this.callbacks[cid]=callback),{remove:function remove(){delete $this.callbacks[cid]}}}}]),events}()},$.pub({generator:function(){function generator(){var $settings=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};if(_classCallCheck(this,generator),$.prv.$.reg[0]&&$.prv.$.reg[0].settings.singleton)return!1;var $id=$.prv.$.lid;$.prv.$.lid++,$.prv.$.reg[$id]={events:{},settings:$settings},this.$={get id(){return $id},get settings(){return $settings}}}return _createClass(generator,[{key:'register',value:function register(eid){var _this=this,node=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,auto=!(2<arguments.length&&void 0!==arguments[2])||arguments[2];$.prv.$.reg[this.$.id].events[eid]||($.prv.$.reg[this.$.id].events[eid]=new $.prv.events(this.$.id,eid));var args=Array.prototype.slice.call(arguments);if(args=args.slice(3),node&&auto){var _ret=function(){!0===auto&&(auto=eid);var task,tmp=_this;if(!$.fx.isTypeOf(node,NodeList))return task=function(){tmp.dispatch.apply(tmp,[eid,node].concat(Array.prototype.slice.call(arguments),_toConsumableArray(args)))},node.addEventListener(auto,task),{v:{remove:function remove(){node.removeEventListener(auto,task)}}};for(var result=[],_loop=function(i){task=function(){tmp.dispatch.apply(tmp,[eid,node[i]].concat(Array.prototype.slice.call(arguments),_toConsumableArray(args)))},node[i].addEventListener(auto,task),result.push({remove:function remove(){node[i].removeEventListener(auto,task)}})},i=0;i<node.length;i++)_loop(i);return{v:result}}();if('object'===('undefined'==typeof _ret?'undefined':_typeof(_ret)))return _ret.v}}},{key:'dispatch',value:function dispatch(eid,tArg){if($.prv.$.reg[this.$.id].events[eid]){var $rid=this.$.id,args=Array.prototype.slice.call(arguments);return args=args.slice(2),Object.keys($.prv.$.reg[this.$.id].events[eid].callbacks).forEach(function(key){var _$$prv$$$reg$$rid$eve;(_$$prv$$$reg$$rid$eve=$.prv.$.reg[$rid].events[eid].callbacks[key]).call.apply(_$$prv$$$reg$$rid$eve,[tArg?tArg:window].concat(_toConsumableArray(args)))}),!0}return!1}},{key:'remove',value:function remove(eid){delete $.prv.$.reg[this.$.id].events[eid]}},{key:'addCallback',value:function addCallback(eid,cb){var position=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null;return!!($.prv.$.reg[this.$.id].events[eid]&&cb)&&$.prv.$.reg[this.$.id].events[eid].setCallback(cb,position)}}]),generator}()})})(Formatrix);