/*!
*  formatrix 0.4.4 (http://formatrix.org)
*  >> PageConstructor 0.2.0
*
*  Copyright (c) 2016-2020 Germo Moeller / webons.industries
*
*  This source code is licensed under the MIT license found in the
*  LICENSE file in the root directory of this source tree.
*
*////***************************************************************************>
(fx=>{let $=new fx(fx.vbind('lib://webons.io/fx/PageConstructor/')+'events');$.prv={$:{lid:0,reg:{}},events:class{constructor($rid,$eid){let $lid=0;this.$={get rid(){return $rid},get eid(){return $eid},get lid(){$lid=$lid+1;return $lid}};this.name=name;this.callbacks={}}setCallback(callback,position){let $this=this,cid=this.$.lid;if(position==null){this.callbacks[cid]=callback}else{}return{remove(){delete $this.callbacks[cid]}}}}};$.pub({generator:class{constructor($settings={}){if($.prv.$.reg[0]&&$.prv.$.reg[0].settings.singleton){return false}else{let $id=$.prv.$.lid;$.prv.$.lid++;$.prv.$.reg[$id]={events:{},settings:$settings};this.$={get id(){return $id},get settings(){return $settings}}}}register(eid,node=null,auto=true){if(!$.prv.$.reg[this.$.id].events[eid]){$.prv.$.reg[this.$.id].events[eid]=new $.prv.events(this.$.id,eid)}let args=Array.prototype.slice.call(arguments);args=args.slice(3);if(node&&auto){if(auto===true){auto=eid}let tmp=this,task;if(!$.fx.isTypeOf(node,NodeList)){task=function(){tmp.dispatch(eid,node,...arguments,...args)};node.addEventListener(auto,task);return{remove(){node.removeEventListener(auto,task)}}}else{let result=[];for(let i=0;i<node.length;i++){task=function(){tmp.dispatch(eid,node[i],...arguments,...args)};node[i].addEventListener(auto,task);result.push({remove(){node[i].removeEventListener(auto,task)}})}return result}}}dispatch(eid,tArg){if($.prv.$.reg[this.$.id].events[eid]){let $rid=this.$.id,args=Array.prototype.slice.call(arguments);args=args.slice(2);Object.keys($.prv.$.reg[this.$.id].events[eid].callbacks).forEach(function(key){$.prv.$.reg[$rid].events[eid].callbacks[key].call(tArg?tArg:window,...args)});return true}else{return false}}remove(eid){delete $.prv.$.reg[this.$.id].events[eid]}addCallback(eid,cb,position=null){if($.prv.$.reg[this.$.id].events[eid]&&cb){return $.prv.$.reg[this.$.id].events[eid].setCallback(cb,position)}else{return false}}}})})(Formatrix);
